name = "openhouse-3"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".next"

[build]
command = "npm run build"
[build.environment]
NODE_VERSION = "18"

[site]
bucket = ".next" 