name = "openhouse-3"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
output_directory = ".next"

[site]
bucket = ".next/static"

[env.production]
node_compat = true

[build.upload]
format = "service-worker" 