# name = "openhouse"
# main = "src/workers/index.ts"
# compatibility_date = "2024-03-01"
# pages_build_output_dir = ".next" # Temporarily commenting out for proxy mode

[vars]
MY_TEST_VAR = "hello_from_wrangler_vars"
JWT_SECRET = "Zq83vN!@uXP4w$Kt9sLrB^AmE5cG1dYz"  # Using the secret from .dev.vars

[env.production]
name = "openhouse3-prod"
route = "openhouse3.com/*"
zone_id = "your-zone-id"
d1_databases = [
  { binding = "DB", database_name = "openhouse3", database_id = "your-db-id" }
]
kv_namespaces = [
  { binding = "CACHE", id = "your-kv-id", preview_id = "your-preview-kv-id" }
]
vars = { JWT_SECRET = "Zq83vN!@uXP4w$Kt9sLrB^AmE5cG1dYz" }  # Replace with your production secret

[env.staging]
name = "openhouse3-staging"
route = "staging.openhouse3.com/*"
zone_id = "your-zone-id"
d1_databases = [
  { binding = "DB", database_name = "openhouse3_staging", database_id = "your-staging-db-id" }
]
kv_namespaces = [
  { binding = "CACHE", id = "your-staging-kv-id", preview_id = "your-staging-kv-id" }
]
vars = { JWT_SECRET = "Zq83vN!@uXP4w$Kt9sLrB^AmE5cG1dYz" }  # Replace with your staging secret

[env.development]
name = "openhouse-dev"
workers_dev = true
compatibility_date = "2024-02-05"
vars = { JWT_SECRET = "Zq83vN!@uXP4w$Kt9sLrB^AmE5cG1dYz" }  # Replace with your development secret

[site]
bucket = ".next/static"

[[d1_databases]]
binding = "DB"
database_name = "openhouse-local"
database_id = "527c7d53-4926-4c79-bbe6-21121a10f06b"

[[kv_namespaces]]
binding = "CACHE"
id = "99b502ae72564574bb8e2041a983f287"
preview_id = "99b502ae72564574bb8e2041a983f287" 