[build]
command = "npm run build"
publish = ".next"

[build.environment]
NODE_VERSION = "18.20.8"
NEXT_TELEMETRY_DISABLED = "1"

[functions]
node_compat = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200 