name = "openhouse"
main = "src/workers/index.ts"
compatibility_date = "2024-03-01"

[build]
command = "npm run build"

[pages]
build_output_dir = ".next"

[env.production]
name = "openhouse3-prod"
route = "openhouse3.com/*"
zone_id = "your-zone-id"
d1_databases = [
  { binding = "DB", database_name = "openhouse3", database_id = "your-db-id" }
]
kv_namespaces = [
  { binding = "CACHE", id = "your-kv-id", preview_id = "your-preview-kv-id" }
]
vars = { JWT_SECRET = "your-jwt-secret" }

[env.staging]
name = "openhouse3-staging"
route = "staging.openhouse3.com/*"
zone_id = "your-zone-id"
d1_databases = [
  { binding = "DB", database_name = "openhouse3_staging", database_id = "your-staging-db-id" }
]
kv_namespaces = [
  { binding = "CACHE", id = "your-staging-kv-id", preview_id = "your-preview-kv-id" }
]
vars = { JWT_SECRET = "your-staging-jwt-secret" }

[site]
bucket = ".next/static"

[[d1_databases]]
binding = "DB"
database_name = "openhouse"
database_id = "YOUR_D1_DATABASE_ID"

[[kv_namespaces]]
binding = "CACHE"
id = "99b502ae72564574bb8e2041a983f287"
preview_id = "99b502ae72564574bb8e2041a983f287" 