# name = "openhouse"
# main = "src/workers/index.ts"
# compatibility_date = "2024-03-01"
# pages_build_output_dir = ".next" # Temporarily commenting out for proxy mode

# OpenHouse3.0 Cloudflare configuration
name = "openhouse3-0"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".vercel/output/static"

# Environment variables
[vars]
JWT_SECRET = "Zq83vN!@uXP4w$Kt9sLrB^AmE5cG1dYz"
NODE_VERSION = "18.20.8"

# Configure Next.js build
[build]
command = "npm run build"

# Tell Cloudflare to use the correct build output
[site]
bucket = ".vercel/output/static"

# Configure Pages behavior
[env.production]
NODE_VERSION = "18.20.8"
vars = { JWT_SECRET = "Zq83vN!@uXP4w$Kt9sLrB^AmE5cG1dYz" }

# Define the build output directory
[build.upload]
format = "directory"
main = ".vercel/output/static"

# Tell Cloudflare about the functions directory
[[build.upload.rules]]
type = "Pages"
globs = [".vercel/output/functions/**/*"]

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "openhouse-local"
database_id = "527c7d53-4926-4c79-bbe6-21121a10f06b"
migrations_dir = "migrations"

# KV Namespace configuration
[[kv_namespaces]]
binding = "CACHE"
id = "99b502ae72564574bb8e2041a983f287"
preview_id = "99b502ae72564574bb8e2041a983f287" 